# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b258335f07c679f5bc0eadc35d0b9fcef2ae72e4a35d9fb412ccaaaca721515c67c3b0c5e86009b042ae532009f6756c48cc6c2446c692dbc5693b7fc03042a8

test:
  secret_key_base: a8f1bea360b46b5ff0f44382b0aa6e6af49e510402a642c65860bf2cc176d00bfe2d5391688513a226002fd17435957b09d867a603bd155895314c9a819ab750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
